import React from "react";

export default function Section() {
  return (
    <section className="section">
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
      <p>This is the section</p>
    </section>
  );
}
